const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const timePill=$('#timePill'),modeToggle=$('#modeToggle'),panel=$('#appPanel'),panelTitle=$('#panelTitle'),panelContent=$('#panelContent'),notes=$('#notesInput');
const facts=["A black hole's gravity is so strong that even light cannot escape from it.",'The Milky Way contains hundreds of billions of stars.','A day on Venus is longer than a Venus year.','Jupiter is larger than all the other planets combined.'];let fact=0;
function clock(){timePill.textContent=new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}clock();setInterval(clock,30000);
modeToggle.onclick=()=>{const t=['dreamy','dusk','aurora'],n=t[(t.indexOf(document.body.dataset.theme)+1)%t.length];document.body.dataset.theme=n;modeToggle.textContent=n==='dusk'?'Velvet dusk':n==='aurora'?'Aurora bloom':'Dawn mode'};
$('#nextFact').onclick=()=>{$('#factText').textContent=facts[fact=(fact+1)%facts.length]};
const saved=localStorage.getItem('astro-notes');if(saved)notes.value=saved;$('#saveNote').onclick=()=>{localStorage.setItem('astro-notes',notes.value);$('#saveNote').textContent='Saved';setTimeout(()=>$('#saveNote').textContent='Save note',900)};
const content={calendar:'September 2026 · Sun Mon Tue Wed Thu Fri Sat',weather:'24° · Partly cloudy · Humidity 68%',flashcards:'What is a nebula? Tap Next to reveal the answer.',gallery:'Carina Nebula · Your cosmic collection',music:'Cosmic Lullaby · Lo-fi space vibes',astro:'Astro is awake and watching the stars.'};
function openPanel(name){if(name==='home'){panel.classList.remove('open');return}panel.classList.add('open');panelTitle.firstChild.textContent=name[0].toUpperCase()+name.slice(1)+' ';panelContent.textContent=content[name]||'';notes.style.display=name==='notes'?'block':'none';$('#saveNote').style.display=name==='notes'?'inline-block':'none'}
$$('[data-panel]').forEach(btn=>btn.onclick=()=>{ $$('[data-panel]').forEach(x=>x.classList.toggle('active',x===btn));openPanel(btn.dataset.panel)});$('#closePanel').onclick=()=>openPanel('home');$('#musicToggle').onclick=e=>e.currentTarget.textContent=e.currentTarget.textContent==='▶'?'❚❚':'▶';
